# Introdução ao pandas

In [1]:
import pandas as pd
import numpy as np

## Estruturas de dados do Pandas

### Series

In [2]:
# Criando uma Series a partir de uma lista
obj = pd.Series( [4, 7, -5, 3] )
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
# Obtendo os valores da Serie
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [4]:
# Obtendo os índices da Serie
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
# Definindo uma lista com os índices
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
# Filtrando e adicionando novos elementos na Series
obj2['a']

-5

In [8]:
obj2['d'] = 6

obj2[ ['c', 'a', 'd'] ]

c    3
a   -5
d    6
dtype: int64

In [9]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [10]:
# Filtrando a Series de acordo com uma condição
obj2[ obj2 > 0 ]

d    6
b    7
c    3
dtype: int64

### Realizando operações com Series

In [11]:
# Multiplicando os elementos por 2
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [12]:
# Aplicando a função exponencial (np.exp()) para cada elemento 
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

### Checando se um índice existe ou não

In [13]:
'b' in obj2

True

In [14]:
'e' in obj2

False

In [15]:
# Criando uma Series a partir de um dicionário da linguagem Python
sdata = {'Berlin': 35000, 'Frankfurt': 71000, 'Nuremberg': 16000, 'Stuttgart': 5000}
print(type(sdata))
obj3 = pd.Series(sdata)
obj3

<class 'dict'>


Berlin       35000
Frankfurt    71000
Nuremberg    16000
Stuttgart     5000
dtype: int64

In [16]:
# Definindo os índices da Series (atenção aos valores NaN)
index = ['Berlin', 'Nuremberg', 'Frankfurt', 'Brasília']
obj4 = pd.Series(sdata, index=index)
obj4

Berlin       35000.0
Nuremberg    16000.0
Frankfurt    71000.0
Brasília         NaN
dtype: float64

In [17]:
pd.isnull(obj4)

Berlin       False
Nuremberg    False
Frankfurt    False
Brasília      True
dtype: bool

In [18]:
pd.notnull(obj4)

Berlin        True
Nuremberg     True
Frankfurt     True
Brasília     False
dtype: bool

In [19]:
# Outra forma, mesmo resultado
obj4.isnull()
pd.isnull(obj4)

Berlin       False
Nuremberg    False
Frankfurt    False
Brasília      True
dtype: bool

In [20]:
# Somando elementos de uma Serie
obj3 + obj4

Berlin        70000.0
Brasília          NaN
Frankfurt    142000.0
Nuremberg     32000.0
Stuttgart         NaN
dtype: float64

In [21]:
# Alterando o nome dos índices
obj4.index.name = 'cidade'
obj4

cidade
Berlin       35000.0
Nuremberg    16000.0
Frankfurt    71000.0
Brasília         NaN
dtype: float64

In [22]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [23]:
# Redefinindo os índices
obj.index = ['João', 'Maria', 'Antônio', 'Pedro']

In [24]:
obj

João       4
Maria      7
Antônio   -5
Pedro      3
dtype: int64

In [25]:
# Lista de funções e métodos de uma Serie
obj.drop( ['Pedro'] )

João       4
Maria      7
Antônio   -5
dtype: int64

### DataFrame

In [26]:
# Criando um DataFrame a partir de um dicionário em Python
dados = {'estado': ['SP', 'MG', 'MT', 'DF', 'MS', 'SE'],
        'ano': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(dados)

In [27]:
# Visualizando as primeiras linhas
frame.head()

estado   ano  pop
0     SP  2000  1.5
1     MG  2001  1.7
2     MT  2002  3.6
3     DF  2001  2.4
4     MS  2002  2.9

In [28]:
# Nomeando as colunas de outra forma
pd.DataFrame(dados, columns=['estado', 'ano', 'pop'])

estado   ano  pop
0     SP  2000  1.5
1     MG  2001  1.7
2     MT  2002  3.6
3     DF  2001  2.4
4     MS  2002  2.9
5     SE  2003  3.2

In [29]:
# Definindo o nome das colunas e os índices do DataFrame
frame2 = pd.DataFrame(dados, columns=['ano', 'estado', 'pop', 'conta'],
                             index=['um', 'dois', 'três', 'quatro',
                                    'cinco', 'seis'])
frame2

ano estado  pop conta
um      2000     SP  1.5   NaN
dois    2001     MG  1.7   NaN
três    2002     MT  3.6   NaN
quatro  2001     DF  2.4   NaN
cinco   2002     MS  2.9   NaN
seis    2003     SE  3.2   NaN

In [30]:
# df['nome da coluna']
frame2['estado']

um        SP
dois      MG
três      MT
quatro    DF
cinco     MS
seis      SE
Name: estado, dtype: object

In [31]:
# df.nome_da_coluna -> não pode conter espaços em branco
frame2.ano

um        2000
dois      2001
três      2002
quatro    2001
cinco     2002
seis      2003
Name: ano, dtype: int64

In [32]:
# Selecionando apenas uma linha do DataFrame através do nome do índice
frame2.loc['três']

ano       2002
estado      MT
pop        3.6
conta      NaN
Name: três, dtype: object

In [33]:
# Definindo valores para uma coluna
frame2['conta'] = 16.5
frame2

ano estado  pop  conta
um      2000     SP  1.5   16.5
dois    2001     MG  1.7   16.5
três    2002     MT  3.6   16.5
quatro  2001     DF  2.4   16.5
cinco   2002     MS  2.9   16.5
seis    2003     SE  3.2   16.5

In [34]:
frame2['conta'] = np.arange(6.)
frame2

ano estado  pop  conta
um      2000     SP  1.5    0.0
dois    2001     MG  1.7    1.0
três    2002     MT  3.6    2.0
quatro  2001     DF  2.4    3.0
cinco   2002     MS  2.9    4.0
seis    2003     SE  3.2    5.0

In [35]:
val = pd.Series([-1.2, -1.5, -1.7], index=['dois', 'quatro', 'cinco'])
val

dois     -1.2
quatro   -1.5
cinco    -1.7
dtype: float64

In [36]:
# Definindo valores para uma coluna a partir de outra série (atenção aos valores correspondentes)
frame2['conta'] = val
frame2

ano estado  pop  conta
um      2000     SP  1.5    NaN
dois    2001     MG  1.7   -1.2
três    2002     MT  3.6    NaN
quatro  2001     DF  2.4   -1.5
cinco   2002     MS  2.9   -1.7
seis    2003     SE  3.2    NaN

In [37]:
# Criando uma coluna com True/False para região sudeste
frame2['sudeste'] = frame2.estado.isin( ['MG', 'SP', 'ES', 'RJ'] )
frame2

ano estado  pop  conta  sudeste
um      2000     SP  1.5    NaN     True
dois    2001     MG  1.7   -1.2     True
três    2002     MT  3.6    NaN    False
quatro  2001     DF  2.4   -1.5    False
cinco   2002     MS  2.9   -1.7    False
seis    2003     SE  3.2    NaN    False

In [38]:
frame2['cidade_grande'] = frame2['pop'].values > 1.5

In [39]:
frame2

ano estado  pop  conta  sudeste  cidade_grande
um      2000     SP  1.5    NaN     True          False
dois    2001     MG  1.7   -1.2     True           True
três    2002     MT  3.6    NaN    False           True
quatro  2001     DF  2.4   -1.5    False           True
cinco   2002     MS  2.9   -1.7    False           True
seis    2003     SE  3.2    NaN    False           True

In [40]:
# Deletando a coluna criada
del frame2['cidade_grande']

In [41]:
frame2.head()

ano estado  pop  conta  sudeste
um      2000     SP  1.5    NaN     True
dois    2001     MG  1.7   -1.2     True
três    2002     MT  3.6    NaN    False
quatro  2001     DF  2.4   -1.5    False
cinco   2002     MS  2.9   -1.7    False

In [42]:
# Dicionários aninhados
pop = {'São Paulo': {2001: 2.4, 
                     2002: 2.9},
                     
       'Salvador': {2000: 1.5, 
                    2001: 1.7, 
                    2002: 3.6}}

In [43]:
# Criando um DataFrame a partir de dicionários aninhados em Python
frame3 = pd.DataFrame(pop)
frame3

São Paulo  Salvador
2001        2.4       1.7
2002        2.9       3.6
2000        NaN       1.5

In [44]:
# DataFrame transposto
frame3.T

2001  2002  2000
São Paulo   2.4   2.9   NaN
Salvador    1.7   3.6   1.5

In [45]:
# Cria um DataFrame passando os índices (atenção para a correspondência)
pd.DataFrame(pop, index=[2001, 2002, 2003])

São Paulo  Salvador
2001        2.4       1.7
2002        2.9       3.6
2003        NaN       NaN

In [46]:
frame3.head()

São Paulo  Salvador
2001        2.4       1.7
2002        2.9       3.6
2000        NaN       1.5

In [47]:
frame3['Salvador'][:2]

2001    1.7
2002    3.6
Name: Salvador, dtype: float64

In [48]:
frame3.index.name = 'ano'
frame3.columns.name = 'cidade'
frame3

cidade  São Paulo  Salvador
ano                        
2001          2.4       1.7
2002          2.9       3.6
2000          NaN       1.5

In [49]:
frame2.values

array([[2000, 'SP', 1.5, nan, True],
       [2001, 'MG', 1.7, -1.2, True],
       [2002, 'MT', 3.6, nan, False],
       [2001, 'DF', 2.4, -1.5, False],
       [2002, 'MS', 2.9, -1.7, False],
       [2003, 'SE', 3.2, nan, False]], dtype=object)

### Objeto Index

In [50]:
# Selecionando um objeto do tipo Index
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [51]:
index[1:]

Index(['b', 'c'], dtype='object')

In [173]:
# Objetos Index são imutáveis
index[1] = 'd'  # TypeError

TypeError: Index does not support mutable operations

In [53]:
# Passando um objeto Index na criação de uma Series
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [54]:
# Criando uma Serie utilizando o objeto Index
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [55]:
# Checando
obj2.index is labels

True

In [56]:
frame3

cidade  São Paulo  Salvador
ano                        
2001          2.4       1.7
2002          2.9       3.6
2000          NaN       1.5

In [57]:
frame3.columns

Index(['São Paulo', 'Salvador'], dtype='object', name='cidade')

In [58]:
'Fortaleza' in frame3.columns

False

In [59]:
2003 in frame3.index

False

## Funções essenciais

### Alterando o índice

In [60]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [61]:
# Alterando o índice (atenção com a correspondência!)
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [62]:
# Preenchendo os índices com o ítem logo acima
obj3 = pd.Series(['azul', 'amarelo', 'roxo'], index=[0, 2, 4])
obj3

0       azul
2    amarelo
4       roxo
dtype: object

In [63]:
obj3.reindex(range(6))

0       azul
1        NaN
2    amarelo
3        NaN
4       roxo
5        NaN
dtype: object

In [64]:
obj3.reindex(range(6), method='ffill')

0       azul
1       azul
2    amarelo
3    amarelo
4       roxo
5       roxo
dtype: object

In [65]:
# Alterações de índice funcionam também com DataFrames
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [66]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

### Deletando elementos (linhas e colunas)

In [67]:
# Deletando registros através do índice
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [68]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [70]:
obj.drop( ['d', 'c'] )

a    0.0
b    1.0
e    4.0
dtype: float64

In [71]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['São Paulo', 'Belo Horizonte', 'Caxias do Sul', 'Fortaleza'],
                    columns=['um', 'dois', 'três', 'quatro'])
data

um  dois  três  quatro
São Paulo        0     1     2       3
Belo Horizonte   4     5     6       7
Caxias do Sul    8     9    10      11
Fortaleza       12    13    14      15

In [72]:
# Deletando vários registros de uma única vez
data.drop(['São Paulo', 'Belo Horizonte'])

um  dois  três  quatro
Caxias do Sul   8     9    10      11
Fortaleza      12    13    14      15

In [73]:
# Deletando um grupo de colunas
data.drop(['dois', 'quatro'], axis=1)

um  três
São Paulo        0     2
Belo Horizonte   4     6
Caxias do Sul    8    10
Fortaleza       12    14

In [74]:
# Deletando um grupo de colunas (forma mais clara!)
data.drop( ['dois', 'quatro'] , axis='columns')

um  três
São Paulo        0     2
Belo Horizonte   4     6
Caxias do Sul    8    10
Fortaleza       12    14

In [75]:
data

um  dois  três  quatro
São Paulo        0     1     2       3
Belo Horizonte   4     5     6       7
Caxias do Sul    8     9    10      11
Fortaleza       12    13    14      15

In [76]:
data.drop(['dois'], axis='columns', inplace=True)

data = data.drop(['dois'], axis='columns')
data

um  três  quatro
São Paulo        0     2       3
Belo Horizonte   4     6       7
Caxias do Sul    8    10      11
Fortaleza       12    14      15

### Indexação, seleção e filtro

In [77]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [78]:
obj['b']

1.0

In [79]:
obj[1]

1.0

In [80]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [81]:
obj[ ['b', 'a', 'd'] ]

b    1.0
a    0.0
d    3.0
dtype: float64

In [82]:
obj[ [1, 3] ]

b    1.0
d    3.0
dtype: float64

In [83]:
obj[ obj < 2 ]

a    0.0
b    1.0
dtype: float64

In [84]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [85]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [86]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['SP', 'RJ', 'MG', 'AM'],
                    columns=['um', 'dois', 'três', 'quatro'])
data

um  dois  três  quatro
SP   0     1     2       3
RJ   4     5     6       7
MG   8     9    10      11
AM  12    13    14      15

In [87]:
data['dois']

SP     1
RJ     5
MG     9
AM    13
Name: dois, dtype: int32

In [88]:
data[ ['três', 'um'] ]

três  um
SP     2   0
RJ     6   4
MG    10   8
AM    14  12

In [89]:
data[:2]

um  dois  três  quatro
SP   0     1     2       3
RJ   4     5     6       7

In [90]:
data['três'] > 5

SP    False
RJ     True
MG     True
AM     True
Name: três, dtype: bool

In [91]:
data[ data['três'] > 5 ]

um  dois  três  quatro
RJ   4     5     6       7
MG   8     9    10      11
AM  12    13    14      15

In [92]:
data < 5

um   dois   três  quatro
SP   True   True   True    True
RJ   True  False  False   False
MG  False  False  False   False
AM  False  False  False   False

In [93]:
data[ data < 5 ] = 0
data

um  dois  três  quatro
SP   0     0     0       0
RJ   0     5     6       7
MG   8     9    10      11
AM  12    13    14      15

#### Selecionando linhas e colunas com loc e iloc

In [94]:
data.loc['MG', ['dois', 'três']]

dois     9
três    10
Name: MG, dtype: int32

In [95]:
data.iloc[2, [3, 0, 1]]

quatro    11
um         8
dois       9
Name: MG, dtype: int32

In [96]:
data.iloc[2]

um         8
dois       9
três      10
quatro    11
Name: MG, dtype: int32

In [97]:
data.iloc[ [1, 2], [3, 0, 1]]

quatro  um  dois
RJ       7   0     5
MG      11   8     9

In [98]:
data.loc[:,['quatro', 'dois']]

quatro  dois
SP       0     0
RJ       7     5
MG      11     9
AM      15    13

In [99]:
data.iloc[:, :3][data['três'] > 5]

um  dois  três
RJ   0     5     6
MG   8     9    10
AM  12    13    14

### Utilizando números inteiros para indexação

In [100]:
ser = pd.Series(np.arange(3.))

In [101]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [174]:
ser[-1]

KeyError: -1

In [103]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

In [104]:
ser[:1]

0    0.0
dtype: float64

In [105]:
# ATENÇÃO! Segundo índice do loc é inclusivo! 
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

- Link: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html

In [106]:
ser.iloc[:1]

0    0.0
dtype: float64

In [107]:
# Fórmula geral para indexação por índice

[LI(inclusiva):linha_final(exclusiva):passo , CI:CF:passo]

[5:23:3,4:10:2]

### Cálculos com DataFrames e Series podem gerar valores NaN

In [108]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [109]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [110]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [111]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Italia', 'Japão', 'França'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Inglaterra', 'Italia', 'Japão', 'Africa do Sul'])
df1

b    c    d
Italia  0.0  1.0  2.0
Japão   3.0  4.0  5.0
França  6.0  7.0  8.0

In [112]:
df2

b     d     e
Inglaterra     0.0   1.0   2.0
Italia         3.0   4.0   5.0
Japão          6.0   7.0   8.0
Africa do Sul  9.0  10.0  11.0

In [113]:
df1 + df2

b   c     d   e
Africa do Sul  NaN NaN   NaN NaN
França         NaN NaN   NaN NaN
Inglaterra     NaN NaN   NaN NaN
Italia         3.0 NaN   6.0 NaN
Japão          9.0 NaN  12.0 NaN

In [114]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1

A
0  1
1  2

In [115]:
df2

B
0  3
1  4

In [116]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

#### Formas de contornar o problema

In [117]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [118]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [119]:
df2.loc[1, 'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [120]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [121]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [122]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [123]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [124]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### Operações entre DataFrames e Series

In [125]:
arr = np.arange(12.).reshape((3, 4))
arr
arr[0]
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [126]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [127]:
arr[0]

array([0., 1., 2., 3.])

In [128]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [129]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [130]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [131]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [132]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [133]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [134]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [135]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Funções e o método apply

In [136]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.591461 -0.813261  3.075632
Ohio    1.100595  0.013975 -0.720406
Texas  -1.077510 -0.253210 -0.921858
Oregon -0.054144  1.310193  1.863815

In [137]:
np.abs(frame)

b         d         e
Utah    0.591461  0.813261  3.075632
Ohio    1.100595  0.013975  0.720406
Texas   1.077510  0.253210  0.921858
Oregon  0.054144  1.310193  1.863815

In [138]:
f = lambda x: x.max() - x.min()
type(f)

function

In [139]:
frame.apply(f)

b    2.178105
d    2.123455
e    3.997489
dtype: float64

In [140]:
frame.apply(f, axis='columns')

Utah      3.888893
Ohio      1.821000
Texas     0.824300
Oregon    1.917959
dtype: float64

In [141]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -1.077510 -0.813261 -0.921858
max  1.100595  1.310193  3.075632

In [142]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah     0.59  -0.81   3.08
Ohio     1.10   0.01  -0.72
Texas   -1.08  -0.25  -0.92
Oregon  -0.05   1.31   1.86

In [143]:
frame['e'].map(format)

Utah       3.08
Ohio      -0.72
Texas     -0.92
Oregon     1.86
Name: e, dtype: object

### Ordenação e ranqueamento

In [144]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [145]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [146]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [147]:
frame.sort_index(axis='columns')

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [148]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [149]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [150]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values(ascending=False)

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [151]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [152]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [153]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [154]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [155]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [156]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [157]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## Sumarizações e estatísticas descritivas

In [158]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [159]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [160]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [161]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [162]:
df.idxmax()

one    b
two    d
dtype: object

In [163]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [164]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [165]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Contagem de valores e valores únicos

In [166]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [167]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [168]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [169]:
pd.value_counts(obj.values, sort=False)

c    3
d    1
b    2
a    3
dtype: int64

In [170]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [171]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [172]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

## Fim